"""
OutreachRoute Pro — Case Note Model

Case notes follow the R.A.P. format: Reason, Action, Plan.
Notes can be created manually by OA users or auto-generated by system events
(status changes, messages sent, meetings scheduled, documents updated, etc.).
"""

from datetime import datetime, timezone
from extensions import db


class CaseNote(db.Model):
    __tablename__ = "case_notes"

    id = db.Column(db.Integer, primary_key=True)
    applicant_id = db.Column(
        db.Integer, db.ForeignKey("applicants.id"), nullable=False, index=True
    )
    user_id = db.Column(
        db.Integer, db.ForeignKey("users.id"), nullable=False
    )

    # Note type from constants.py CASE_NOTE_TYPES
    note_type = db.Column(db.String(100), nullable=True)

    # R.A.P. fields
    reason = db.Column(db.Text, nullable=True)
    action = db.Column(db.Text, nullable=True)
    plan = db.Column(db.Text, nullable=True)

    # Full composed note body (auto-filled from RAP fields or free-form)
    note_body = db.Column(db.Text, nullable=True)

    # True if generated automatically by the system (status change, message sent, etc.)
    auto_generated = db.Column(db.Boolean, default=False)

    created_at = db.Column(
        db.DateTime, default=lambda: datetime.now(timezone.utc), index=True
    )

    # ── Relationships ────────────────────────────────────────────────────────
    applicant = db.relationship("Applicant", back_populates="case_notes")
    user = db.relationship("User", back_populates="case_notes")

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "applicant_id": self.applicant_id,
            "user_id": self.user_id,
            "user": self.user.to_dict() if self.user else None,
            "note_type": self.note_type,
            "reason": self.reason,
            "action": self.action,
            "plan": self.plan,
            "note_body": self.note_body,
            "auto_generated": self.auto_generated,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }

    def __repr__(self):
        kind = "auto" if self.auto_generated else "manual"
        return f"<CaseNote [{kind}] applicant={self.applicant_id}>"
